name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Bun 🥟
        uses: oven-sh/setup-bun@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@inkdropapp'

      - name: Install 🔧
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: bun install

      - name: Generate Palette 🏗️
        run: ./bin/generate-palette
